FORMAT: 1A

# Agent/Adapter API

The most important part of VICINITY Agent is the VICINITY Adapter subcomponent. 
Adapter serves as the proxy between common VICINITY services and underlying infrastructure. 
For each specific infrastructure to be integrated, there must exist specific VICINITY Adapter. 
The role of Adapter is to translate VICINITY services into infrastructure specific services. 
VICINITY Adapter provides the API, which must be implemented, when integrating new 
infrastructure.

## IoT objects [/things]

### List All IoT objects [GET]

+ Response 200 (application/json)

        [
            {
                "name": "stars1",
                "id": "c5121251-a20f-46f0-afb7-f32e7fa54693",
                "type": [
                    "s4all:Photometer"
                ],
                "deviceInfo": [{
                    "key": "value"
                }],
                "infrastructureID": "infrastructure_id",
                "services": [{
                    "type": "property/action",
                    "id": "5cf59515-516c-4e2a-b84f-a3cafc170f3e",
                    "name": "tamb",
                    "input": [],
                    "output": [],
                    "serviceInfo": [{
                        "key": "value"
                    }]
                }]
            }
        ]

## IoT object's property/action [/things/{thing_id}/properties/{service_id}]

+ Parameters
    + thing_id (guid) - ID of the IoT thing in the underlying infrastructure in the form of an GUID
    + service_id (guid) - name of the service supported by the thing in the form of an GUID

### Calling a service [PUT]

Get/Set a value of corresponding property/action of the IoT object maitained by the underlying IoT
infrastructure.

+ Request (application/json)

        {
            "filter": {
                "from": "iso_date_time",
                "to": "iso_date_time",
                "limit": 10
            }
            "actionData": [{
                    "key": "value"
            }]
        }

+ Response 200 (application/json)
        
        [
            {
                "value": [{
                    "key": "value"
                }]
            }
        ]